Reworked volume control
Back from using easier "mpc volume" to amixer to be more compatible with external DAC which mpd/mpc might not recognise without editing /etc/mpd.conf (setting mixer_control to "Digital" worked for me when using IQaudio DAC Zero).

diff --git a/piradio b/piradio
--- a/piradio
+++ b/piradio
@@ -4,11 +4,11 @@
 # Made by    : Ewoud Dronkert
 # Licence    : GNU GPL v3
 # Platform   : Raspberry Pi
-# Requires   : bash, mpd, mpc, at
+# Requires   : bash, mpd, mpc, amixer, bc, at
 # Location   : /usr/local/bin/
 # Name       : piradio
-# Version    : 1.2.0
-# Date       : 2016-06-14
+# Version    : 1.3.0
+# Date       : 2016-07-09
 # Purpose    : Play radio streams via local mpd audio server
 #              Use station abbreviations from user file radio.txt
 #              Shutdown (auto-off) after 3 hours using 'at'
@@ -23,12 +23,14 @@
 #######################################################################
 
 # Variables
-PLAYER=$(which mpc)
-ATBIN=$(which at)
+PLAYER=/usr/bin/mpc
+MIXER=/usr/bin/amixer
+BCBIN=/usr/bin/bc
+ATBIN=/usr/bin/at
 ATCMD="$PLAYER stop"
 PIHOME=$(cat /etc/passwd | grep -e '^pi:' | cut -d':' -f6)
 DBFILE=$PIHOME/radio.txt
-DEFVOL=85
+DEFVOL=60
 ADJVOL=5
 
 # Error codes
@@ -51,6 +53,20 @@ if [ ! -x "$PLAYER" ]; then
 	exit $ERR_APPNOTFOUND
 fi
 
+if [ ! -x "$MIXER" ]; then
+	echo | StdErr
+	echo "   Mixer for volume control not found: $MIXER" | StdErr
+	echo | StdErr
+	exit $ERR_APPNOTFOUND
+fi
+
+if [ ! -x "$BCBIN" ]; then
+	echo | StdErr
+	echo "   Calc tool for volume control not found: $BCBIN" | StdErr
+	echo | StdErr
+	exit $ERR_APPNOTFOUND
+fi
+
 if [ ! -x "$ATBIN" ]; then
 	echo | StdErr
 	echo "   Scheduler for snooze not found: $ATBIN" | StdErr
@@ -58,10 +74,8 @@ if [ ! -x "$ATBIN" ]; then
 	exit $ERR_APPNOTFOUND
 fi
 
-# "at" with sudo because the script might be called from the web interface
-# as user www-data who is in /etc/at.deny. That then requires using visudo
-# to add /usr/bin/at for user www-data. If only called from command line as
-# user pi, sudo may be removed.
+# "at" with sudo to catch scheduled times across all users
+# Requires visudo: add /usr/bin/at for user www-data
 function SnoozeClear () {
 	for i in $(sudo $ATBIN -l | grep -oP '^\d+' | sort | xargs); do
 		j=$(sudo $ATBIN -c $i | tail -n 1)
@@ -76,16 +90,32 @@ function SnoozeReset () {
 	echo -n "$ATCMD" | sudo $ATBIN -M now + 3 hours &> /dev/null
 }
 
+# Return earliest snooze time via standard out
 function SnoozeFind () {
-	RETVAL=
 	for i in $(sudo $ATBIN -l | grep -oP '^\d+' | sort | xargs); do
 		j=$(sudo $ATBIN -c $i | tail -n 1)
 		if [[ "$j" == "$ATCMD" ]]; then
-			RETVAL=$(sudo $ATBIN -l | grep -P "^$i\t" | cut -d" " -f5 | cut -d":" -f1-2)
-			return $ERR_OK
+			sudo $ATBIN -l | grep -P "^$i\t" | cut -d" " -f5 | cut -d":" -f1-2
 		fi
 	done
-	return $ERR_NOSNOOZE
+}
+
+# Returns volume as a percantage 0-100 via standard out
+function GetVolume () {
+	GET=$($MIXER cget numid=1)
+	MIN=$(echo "$GET" | /bin/grep -oE ',min=[^,]+' | /bin/grep -oE '[0-9-]+')
+	MAX=$(echo "$GET" | /bin/grep -oE ',max=[^,]+' | /bin/grep -oE '[0-9-]+')
+	VAL=$(echo "$GET" | /bin/grep -oE ': values=[0-9+-]+' | /bin/grep -oE '[0-9-]+')
+	echo "(100*($VAL-($MIN))+0.5*($MAX-($MIN)))/($MAX-($MIN))" | $BCBIN
+}
+
+# Required argument: volume as a percentage 0-100
+function SetVolume () {
+	VOL="${1//[^0-9]/}"
+	LEN=${#VOL}
+	if (( LEN >= 1 && LEN <= 3 && VOL >= 0 && VOL <= 100 )); then
+		$MIXER -q cset numid=1 -- "${VOL}%"
+	fi
 }
 
 # Help
@@ -106,13 +136,15 @@ fi
 
 # Display current station/stream/volume if no argument
 if [ -z "$1" ]; then
-	curvolume=$($PLAYER volume | grep --colour=never -m 1 -oP '\d+')
+	curvolume=$(GetVolume)
 	curstream=$($PLAYER -f "%file%" current)
 	if [ -z "$curstream" ]; then
 		curstation="(no stream found)"
 	else
 		if [ -f $DBFILE ]; then
-			curstation=$(cat $DBFILE | grep --colour=never -m 1 -F "$curstream" | grep --colour=never -oP '^\S+')
+			curstation=$(cat $DBFILE \
+				| grep --colour=never -m 1 -F "$curstream" \
+				| grep --colour=never -oP '^\S+')
 			if [ -z "$curstation" ]; then
 				curstation="(station not found)"
 			fi
@@ -120,8 +152,7 @@ if [ -z "$1" ]; then
 			curstation="(station database not found at \"$DBFILE\")"
 		fi
 	fi
-	SnoozeFind
-	snooze=$RETVAL
+	snooze=$(SnoozeFind)
 	echo
 	[ -z "$curstation" ] || echo "   Station : $curstation"
 	[ -z "$curstream" ]  || echo "   Stream  : $curstream"
@@ -164,7 +195,7 @@ fi
 
 # Display volume, optionally set or adjust or mute/unmute
 if [[ "$1" == "vol" || "$1" == "mute" ]]; then
-	declare -i curvol=$($PLAYER volume | grep --colour=never -m 1 -oP '\d+')
+	declare -i curvol=$(GetVolume)
 	declare -i newvol=$curvol
 	declare -i minvol=10
 	declare -i maxvol=100
@@ -195,7 +226,7 @@ if [[ "$1" == "vol" || "$1" == "mute" ]]; then
 	fi
 	if (( newvol != curvol )); then
 		# volume adjustment
-		$PLAYER volume $newvol > /dev/null
+		SetVolume $newvol
 		curvol=$newvol
 	fi
 	echo
@@ -207,8 +238,12 @@ fi
 # Argument is a Station ID
 # Escape argument for use with grep -P
 # Is it really safe? Not sure. Couldn't make escaping ] work, for instance.
-safe=$(echo "$1" | sed -e 's/\s*//g' | sed -e 's/[\[\\^$.*?"-]/\\\0/g')
-[ -f $DBFILE ] && stream=$(cat $DBFILE | grep --color=never -m 1 -P "^$safe\s" | grep --color=never -oP '\S+$')
+safe=$(echo "$1" \
+	| sed -e 's/\s*//g' \
+	| sed -e 's/[\[\\^$.*?"-]/\\\0/g')
+[ -f $DBFILE ] && stream=$(cat $DBFILE \
+	| grep --color=never -m 1 -P "^$safe\s" \
+	| grep --color=never -oP '\S+$')
 
 if [ -z "$stream" ]; then
 	echo | StdErr
